In [1]:
# This R environment comes with many helpful analytics packages installed
# It is defined by the kaggle/rstats Docker image: https://github.com/kaggle/docker-rstats
# For example, here's a helpful package to load

library(tidyverse) # metapackage of all tidyverse packages

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

list.files(path = "../input")

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──

✔ ggplot2 3.3.2     ✔ purrr   0.3.4
✔ tibble  3.0.3     ✔ dplyr   1.0.2
✔ tidyr   1.1.2     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.5.0

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()



character(0)

In [2]:
# My first program in R Programming
myString <- "Hello, World!.Welcome to R Session"

In [3]:
print(myString)

[1] "Hello, World!.Welcome to R Session"


# Vectors
# When you want to create vector with more than one element, you should use c() function which means to combine the elements into a vector.

In [4]:
# Create a vector.
drinks <- c('wine','beer',"whiskey")
print(drinks)

[1] "wine"    "beer"    "whiskey"


In [5]:
# Get the class of the vector.
print(class(drinks))

[1] "character"


# LIST
# A list is an R-object which can contain many different types of elements inside it like vectors, functions and even another list inside it.

In [6]:
# Create a list.
New_list <- list(c(1,3,3,2,6,1,2,5,3),21.3,22.3,22.9,20.1,sin,cos,tan)

In [7]:
New_list

[[1]]
[1] 1 3 3 2 6 1 2 5 3

[[2]]
[1] 21.3

[[3]]
[1] 22.3

[[4]]
[1] 22.9

[[5]]
[1] 20.1

[[6]]
function (x)  .Primitive("sin")

[[7]]
function (x)  .Primitive("cos")

[[8]]
function (x)  .Primitive("tan")

# Matrices
# A matrix is a two-dimensional rectangular data set. It can be created using a vector input to the matrix function.

In [8]:
# Create a matrix.
My_Matrix = matrix( c('2','1','10','3','9','1','2','0','1'), nrow = 3, ncol = 3, byrow = TRUE)

In [9]:
My_Matrix

[,1] [,2] [,3]
[1,] 2    1    10  
[2,] 3    9    1   
[3,] 2    0    1

# Arrays
# While matrices are confined to two dimensions, arrays can be of any number of dimensions. The array function takes a dim attribute which creates the required number of dimension. In the below example we create an array with two elements which are 3x3 matrices each.

In [10]:
# Create an array.
My_Array <- array(c('Black','White'),dim = c(3,3,3))
print(My_Array)

, , 1

     [,1]    [,2]    [,3]   
[1,] "Black" "White" "Black"
[2,] "White" "Black" "White"
[3,] "Black" "White" "Black"

, , 2

     [,1]    [,2]    [,3]   
[1,] "White" "Black" "White"
[2,] "Black" "White" "Black"
[3,] "White" "Black" "White"

, , 3

     [,1]    [,2]    [,3]   
[1,] "Black" "White" "Black"
[2,] "White" "Black" "White"
[3,] "Black" "White" "Black"



# Factors
# Factors are the r-objects which are created using a vector. It stores the vector along with the distinct values of the elements in the vector as labels. The labels are always character irrespective of whether it is numeric or character or Boolean etc. in the input vector. They are useful in statistical modeling.
# Factors are created using the factor() function. The nlevels functions gives the count of levels.

In [11]:
# Create a vector.
My_colors <- c('blue','blue','white','black','green','yellow','red','red','red','green')

# Create a factor object.
factor_colour <- factor(My_colors)

# Print the factor.
print(factor_colour)
print(nlevels(factor_colour))

 [1] blue   blue   white  black  green  yellow red    red    red    green 
Levels: black blue green red white yellow
[1] 6


# Data Frames
# Data frames are tabular data objects. Unlike a matrix in data frame each column can contain different modes of data. The first column can be numeric while the second column can be character and third column can be logical. It is a list of vectors of equal length.
# Data Frames are created using the data.frame() function.

In [12]:
# Create the data frame.
My_DataFrame <- data.frame(
   Gender = c("Male", "Male","Male","Female","Female","Male"), 
   Height = c(152, 171.5, 165,182,178,170.5), 
   Weight = c(81,93,78,82,67,80),
   Age = c(42,38,26,39,28,21),
   Profession= c("Self-employed","Teacher","Banker","Sale","Clerk","Teacher")
)
print(My_DataFrame)

  Gender Height Weight Age    Profession
1   Male  152.0     81  42 Self-employed
2   Male  171.5     93  38       Teacher
3   Male  165.0     78  26        Banker
4 Female  182.0     82  39          Sale
5 Female  178.0     67  28         Clerk
6   Male  170.5     80  21       Teacher


# Variable Assignment
# The variables can be assigned values using leftward, rightward and equal to operator. The values of the variables can be printed using print() or cat() function. The cat() function combines multiple items into a continuous print output.

In [13]:
# Assignment using equal operator.
var.1 = c(1,2,2,2,3,6,3,2)           

# Assignment using leftward operator.
var.2 <- c("Learn","Python","Not","R")   

# Assignment using rightward operator.   
c(TRUE,1) -> var.3           

print(var.1)
cat ("var.1 is ", var.1 ,"\n")
cat ("var.2 is ", var.2 ,"\n")
cat ("var.3 is ", var.3 ,"\n")

[1] 1 2 2 2 3 6 3 2
var.1 is  1 2 2 2 3 6 3 2 
var.2 is  Learn Python Not R 
var.3 is  1 1 


# To be continued ....... 